package main

func main() {
	twosum_print()
	palindrome()
	romanint()
	prefixinit()
	lengthsubstringinit()
	twoNumbersinit()
	palindromicsubstringinit()
	zigzagconversioninit()
	reverseinit()
	minScoreinit()
	AtoiInit()
	findMedianInit()
	isMatchInit()
	maxAreaInit()
	integerromanint()
	englishformatinit()
	threeSumInit()
	closedIslandInit()
	threeSumClosestInit()
	fourSumInit()
	lettercombinationinit()
}